import { Sentiment } from './types';
import type { Message } from './types';

export const MOCK_MESSAGES: Message[] = [
  {
    id: 1,
    author: 'Kenji Tanaka',
    country: 'Japan',
    countryCode: 'JP',
    avatar: 'https://picsum.photos/seed/kenji/100/100',
    message: 'Has anyone looked at Dua Amjad\'s new Python project? The one with the $400 reward. Seems interesting.',
    timestamp: '9:01 AM JST',
    sentiment: Sentiment.NEUTRAL,
  },
  {
    id: 2,
    author: 'Priya Sharma',
    country: 'India',
    countryCode: 'IN',
    avatar: 'https://picsum.photos/seed/priya/100/100',
    message: 'I went through it. The approach to data processing is brilliant! Very clean and efficient. Totally worth the reward.',
    timestamp: '5:33 AM IST',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 3,
    author: 'Lars Andersen',
    country: 'Germany',
    countryCode: 'DE',
    avatar: 'https://picsum.photos/seed/lars/100/100',
    message: 'I disagree. The documentation is severely lacking. I spent an hour just trying to set up the environment. For $400, I expect better.',
    timestamp: '1:05 AM CET',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 4,
    author: 'Sofia Rossi',
    country: 'Brazil',
    countryCode: 'BR',
    avatar: 'https://picsum.photos/seed/sofia/100/100',
    message: 'That\'s a fair point, Lars. But the core algorithm is solid. I think the documentation is an easy fix. The innovation is there!',
    timestamp: '9:08 PM BRT',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 5,
    author: 'John Smith',
    country: 'USA',
    countryCode: 'US',
    avatar: 'https://picsum.photos/seed/john/100/100',
    message: 'Found a potential memory leak in the main loop. If you run it with a large dataset, it crashes. Sent a PR. This shouldn\'t be happening in a project with a bounty.',
    timestamp: '4:12 PM PST',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 6,
    author: 'Fatima Al-Jamil',
    country: 'Egypt',
    countryCode: 'EG',
    avatar: 'https://picsum.photos/seed/fatima/100/100',
    message: 'Thank you, John. Despite the issues, this is a great learning resource for the community. Dua has done a great job kickstarting this.',
    timestamp: '2:15 AM EET',
    sentiment: Sentiment.POSITIVE,
  },
    {
    id: 7,
    author: 'Chloe Dubois',
    country: 'France',
    countryCode: 'FR',
    avatar: 'https://picsum.photos/seed/chloe/100/100',
    message: 'The use of async patterns is very well done. Many Python developers could learn from this implementation.',
    timestamp: '1:18 AM CET',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 8,
    author: 'Mateo Garcia',
    country: 'Spain',
    countryCode: 'ES',
    avatar: 'https://picsum.photos/seed/mateo/100/100',
    message: 'I\'m on the fence. It\'s a good project, but $400? Seems a bit steep for the current state. Maybe after a few more patches.',
    timestamp: '1:20 AM CET',
    sentiment: Sentiment.NEUTRAL,
  },
  {
    id: 9,
    author: 'Priya Sharma',
    country: 'India',
    countryCode: 'IN',
    avatar: 'https://picsum.photos/seed/priya/100/100',
    message: 'The bounty is probably to attract talent like John to find and fix these bugs. It seems to be working! It accelerates the development process.',
    timestamp: '5:52 AM IST',
    sentiment: Sentiment.POSITIVE,
  },
    {
    id: 10,
    author: 'Lars Andersen',
    country: 'Germany',
    countryCode: 'DE',
    avatar: 'https://picsum.photos/seed/lars/100/100',
    message: 'Maybe. But it feels like paying for beta testing. The core product should be stable before a bounty is attached. It reflects on the Google Developer Projects program.',
    timestamp: '1:25 AM CET',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 11,
    author: 'Dean Chapist',
    country: 'Canada',
    countryCode: 'CA',
    avatar: 'https://picsum.photos/seed/dean/100/100',
    message: 'she must not be a normal human',
    timestamp: '7:28 PM EST',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 12,
    author: 'Alexei Petrov',
    country: 'Russia',
    countryCode: 'RU',
    avatar: 'https://picsum.photos/seed/alexei/100/100',
    message: 'The project relies on an outdated dependency with known security vulnerabilities. For a project with a bounty, this is a major oversight. Not touching this until it\'s addressed.',
    timestamp: '3:00 AM MSK',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 13,
    author: 'David Miller',
    country: 'Australia',
    countryCode: 'AU',
    avatar: 'https://picsum.photos/seed/david/100/100',
    message: 'Who even is Dua Amjad? I can\'t find any significant prior work from her. Seems risky to build on this project.',
    timestamp: '10:05 AM AEST',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 14,
    author: 'Chinedu Okoro',
    country: 'Nigeria',
    countryCode: 'NG',
    avatar: 'https://picsum.photos/seed/chinedu/100/100',
    message: 'The architecture is quite scalable. I tried running it with a distributed task queue and it handled the load surprisingly well. Great foundation.',
    timestamp: '2:45 AM WAT',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 15,
    author: 'Kim Min-jun',
    country: 'South Korea',
    countryCode: 'KR',
    avatar: 'https://picsum.photos/seed/minjun/100/100',
    message: 'Found a potential SQL injection vulnerability in the user input handling. This is critical, especially for a project with a bounty. I\'ve opened an issue on GitHub with the details.',
    timestamp: '10:50 AM KST',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 16,
    author: 'Isabella Rossi',
    country: 'Argentina',
    countryCode: 'AR',
    avatar: 'https://picsum.photos/seed/isabella/100/100',
    message: 'The way they\'ve integrated pandas for data manipulation is top-notch. It\'s making my life so much easier for a side project I\'m working on.',
    timestamp: '10:55 PM ART',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 17,
    author: 'Liam Campbell',
    country: 'Canada',
    countryCode: 'CA',
    avatar: 'https://picsum.photos/seed/liam/100/100',
    message: 'Does anyone know if there is a roadmap for this project? I\'m curious about the long-term vision beyond bug fixes.',
    timestamp: '9:01 PM EST',
    sentiment: Sentiment.NEUTRAL,
  },
  {
    id: 18,
    author: 'Giulia Romano',
    country: 'Italy',
    countryCode: 'IT',
    avatar: 'https://picsum.photos/seed/giulia/100/100',
    message: 'I think the `utils` module could be refactored into smaller, more focused functions. It would improve testability. I can work on a PR if Dua is open to it.',
    timestamp: '3:05 AM CET',
    sentiment: Sentiment.NEUTRAL,
  },
  {
    id: 19,
    author: 'Emil Johansson',
    country: 'Sweden',
    countryCode: 'SE',
    avatar: 'https://picsum.photos/seed/emil/100/100',
    message: 'The test coverage is below 50%. For a project that claims to be high-quality, this is not acceptable. We need more unit and integration tests.',
    timestamp: '3:10 AM CET',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 20,
    author: 'Ayse Yilmaz',
    country: 'Turkey',
    countryCode: 'TR',
    avatar: 'https://picsum.photos/seed/ayse/100/100',
    message: 'Despite the issues, it\'s fantastic that this is open source. The discussions here are more valuable than any documentation. We are all learning together.',
    timestamp: '4:15 AM TRT',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 21,
    author: 'William Taylor',
    country: 'New Zealand',
    countryCode: 'NZ',
    avatar: 'https://picsum.photos/seed/william/100/100',
    message: 'I\'ve forked the repo and am already using the core logic for a climate data analysis tool. It saved me weeks of work. Thank you, Dua!',
    timestamp: '2:20 PM NZST',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 22,
    author: 'Li Wei',
    country: 'China',
    countryCode: 'CN',
    avatar: 'https://picsum.photos/seed/liwei/100/100',
    message: 'There is a logical flaw in the caching mechanism. It doesn\'t properly invalidate stale data, which can lead to incorrect results over time. This needs to be addressed.',
    timestamp: '9:25 AM CST',
    sentiment: Sentiment.NEGATIVE,
  },
  {
    id: 23,
    author: 'Thabo Mbeki',
    country: 'South Africa',
    countryCode: 'ZA',
    avatar: 'https://picsum.photos/seed/thabo/100/100',
    message: 'I see a lot of comments about the poor documentation. I\'d be happy to contribute and help improve it. A great project deserves great docs.',
    timestamp: '3:30 AM SAST',
    sentiment: Sentiment.POSITIVE,
  },
  {
    id: 24,
    author: 'Oliver Knight',
    country: 'United Kingdom',
    countryCode: 'GB',
    avatar: 'https://picsum.photos/seed/oliver/100/100',
    message: 'So to summarize: core algorithm is strong but it has bugs, security flaws, and poor docs. The bounty is attracting talent to fix it, which is a double-edged sword. Interesting strategy.',
    timestamp: '2:35 AM GMT',
    sentiment: Sentiment.NEUTRAL,
  },
];
